defaults:
  - logger: logger
  - arch: anakin
  - system: ppo/ff_ippo
  - network: mlp  # [mlp, cnn]
  - env: ipd-squared # jax-party  # [cleaner, connector, vector-connector, gigastep, lbf, mabrax, matrax, rware, smax, mpe]
  - vault: party_vault
  - _self_

hydra:
  searchpath:
    - file://mava/configs
