defaults:
  - logger: logger
  - arch: anakin
  - system: ppo/ff_ippo
  - network: mlp  # [mlp, cnn]
  - env: ipd-squared  # [cleaner, connector, vector-connector, gigastep, lbf, mabrax, matrax, rware, smax, mpe]
  - vault: config-vault
  - _self_

hydra:
  searchpath:
    - file://mava/configs
