defaults:
  - logger: logger
  - arch: anakin
  - system: sable/ff_sable
  - network: ff_retention
  - env: rware  # [cleaner, connector, gigastep, lbf, rware, smax]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
