defaults:
  - logger: logger
  - arch: anakin
  - system: sable/rec_sable
  - network: rec_retention
  - env: rware   # [cleaner, connector, vector-connector, gigastep, lbf, matrax, rware, smax]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
