name: Integration Tests: 🧪

on:
  push:
    branches:
      - develop

jobs:
  integration-tests:
    name: "Python ${{ matrix.python-version }} on ubuntu-latest"
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout mava
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.26"
          enable-cache: true
          cache-dependency-glob: "requirements/requirements**.txt"  # invalidate cache when requirements file changes

      - uses: actions/setup-python@v5
        with:
            python-version: "${{ matrix.python-version }}"

      - name: Install python dependencies 🔧
        run: uv pip install .[dev]
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Run integration tests 🧪
        run: pytest test/integration_test.py -p no:warnings
