name: Tests and Linters 🧪

on: [ pull_request ]

jobs:
  tests-and-linters:
    name: "Python ${{ matrix.python-version }} on ubuntu-latest"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout mava
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.26"
          enable-cache: true
          cache-dependency-glob: "requirements/requirements**.txt"  # invalidate cache when requirements file changes

      - uses: actions/setup-python@v5
        with:
            python-version: "${{ matrix.python-version }}"

      - name: Install python dependencies 🔧
        run: uv pip install .[dev]
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Run linters 🖌️
        run: pre-commit run --all-files --verbose

      - name: Run tests 🧪
        run: pytest -p no:warnings
